#!/usr/bin/env bash
# Displays To infinity and beyond indefinitely
# With a sleep 2 and I am invincible!!! when get a SIGTERM signal
trap 'echo "I am invincible!!!"; exit' SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
done
