#!/usr/bin/env bash
#Gives information about the school file
if [ -e school ]
then
	echo "school file exists"
	if [ -s school ]
	then
		echo "school file is empty"
	elif [ -f school ]
	then
		echo "school is a regular file"
	else
		echo "school file is not empty"
	fi
else
	echo "school file does not exist"
fi
