#!/usr/bin/env bash
#Gives information about the school file
if [ file != 0 ]
then
echo "school file exists"
	if [ -s file ]
	then
		echo "school file is empty"
	elif [ -f file ]
	then
		echo "school is a regular file"
	else
		echo "school file is not empty"
	fi
else
echo "school file does not exist"
fi
